I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script call
    call LB_TEXAS_HOLDEM()
  File "game/z_Class_Poker.rpy", line 337, in script
    $ winner = HANDS_COMPARE(player.hand, computer.hand, cards_open)
  File "game/z_Class_Poker.rpy", line 337, in <module>
    $ winner = HANDS_COMPARE(player.hand, computer.hand, cards_open)
  File "game/z_Class_Poker.rpy", line 137, in HANDS_COMPARE
    player_evaluated = HAND_EVALUATE(player_hand, list(cards_open))
  File "game/z_Class_Poker.rpy", line 179, in HAND_EVALUATE
    unique_ranks_values = sorted(list(set(_rank_to_value(card['rank']) for card in combined)), reverse=True)            # ═══► Check for Straight
NameError: name '_rank_to_value' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script call
    call LB_TEXAS_HOLDEM()
  File "game/z_Class_Poker.rpy", line 337, in script
    $ winner = HANDS_COMPARE(player.hand, computer.hand, cards_open)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Volumes/INTERNAL_NVM/Games/RenPy SDK/renpy/python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/z_Class_Poker.rpy", line 337, in <module>
    $ winner = HANDS_COMPARE(player.hand, computer.hand, cards_open)
  File "game/z_Class_Poker.rpy", line 137, in HANDS_COMPARE
    player_evaluated = HAND_EVALUATE(player_hand, list(cards_open))
  File "game/z_Class_Poker.rpy", line 179, in HAND_EVALUATE
    unique_ranks_values = sorted(list(set(_rank_to_value(card['rank']) for card in combined)), reverse=True)            # ═══► Check for Straight
NameError: name '_rank_to_value' is not defined

macOS-15.5-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Poker 1.0
Sun Jun 15 21:05:24 2025
